apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog
  namespace: caddy-system
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
  selector:
    app: blog
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog
  name: blog
  namespace: caddy-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog
    spec:
      containers:
        - image: youeclipse/blog
          name: blog
          ports:
            - containerPort: 80
          env:
            # - name: NODE_NAME
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: spec.nodeName

          resources: {}
