apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog
  namespace: golang-im
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
  selector:
    app: blog
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog
  name: blog
  namespace: golang-im
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  strategy: {}
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - image: youeclipse/blog:latest
          name: blog
          ports:
            - containerPort: 80 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: golang-im
spec:
  rules:
    - host: blog.golang.im
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: blog
                port: 
                  number: 80
