apiVersion: v1
kind: Service
metadata:
  labels:
    app: plantuml
  name: plantuml
  namespace: golang-im
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 443
      name: https
      protocol: TCP
      targetPort: 8080
  selector:
    app: plantuml
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plantuml
  name: plantuml
  namespace: golang-im
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantuml
  strategy: {}
  template:
    metadata:
      labels:
        app: plantuml
    spec:
      containers:
        - image: plantuml/plantuml-server:tomcat
          name: plantuml
          ports:
            - containerPort: 8080
          resources: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: golang-im
spec:
  rules:
    - host: plantuml.golang.im
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: plantuml
                port: 
                  number: 80
