apiVersion: v1
kind: Service
metadata:
  labels:
    app: plantuml
  name: plantuml
  namespace: kube-system
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 443
      name: https
      protocol: TCP
      targetPort: 8080
  selector:
    app: plantuml
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plantuml
  name: plantuml
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantuml
  strategy: {}
  template:
    metadata:
      labels:
        app: plantuml
    spec:
      containers:
        - image: plantuml/plantuml-server:tomcat
          name: plantuml
          ports:
            - containerPort: 8080

          resources: {}
