apiVersion: v1
kind: Service
metadata:
  labels:
    app: website
  name: website
  namespace: kube-system
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
  selector:
    app: website
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: website
  name: website
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  strategy: {}
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image: youeclipse/golang.im:latest
          name: website
          ports:
            - containerPort: 80
